### ISSUE TITLE
When to release v3.0?

### ISSUE THREAD

**Issue by hszhakka** [jekyll/minima#422]
I know I can use the latest version of minima through [`jekyll-remote-theme`](https://github.com/benbalter/jekyll-remote-theme), but it reports an error: 

```
`configure_theme': undefined method `configure_sass' for #<Jekyll::RemoteTheme::Theme:0x00007fef2f96dfb8> (NoMethodError)
```

See https://github.com/benbalter/jekyll-remote-theme/pull/61

So I want to directly use minima. Please release v3.0 quickly, thanks.

**Comment by ashmaroli** [comment]
@hszhakka Please be patient. Minima 3.0 will be released when it is ready.

If you plan to use Minima 3.0 via GitHub Pages, you'll have to wait much longer because Minima 3.0 contains numerous breaking changes. GitHub Pages won't be able to upgrade immediately after Minima 3.0 releases because the sites currently using Minima 2.x will break.

The issue with `jekyll-remote-theme` only affects builds with Jekyll 4.0. GitHub Pages uses Jekyll 3.8.6. So you should be able to use `remote_theme: jekyll/minima` without issues on GitHub Pages.

If you must use Jekyll 4.0, what you can do is point your Gemfile to this repository, build locally and then push the contents of `_site` to a branch named `gh-pages`:
```ruby
# Gemfile

gem "jekyll", "~> 4.0"
gem "minima", github: "jekyll/minima"
```
